config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("jobprofile.users.urls", namespace="users")),
    path("candidate/", include("candidate.urls", namespace="candidate")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

jobprofile/candidate/urls.py
from django.urls import path

from jobprofile.candidate.views import CreateCandidateProfileView

app_name = "candidate"

urlpatterns = [
    path("candidate/", view=CreateCandidateProfileView.as_view(), name="candidate"),
]

jobprofile/users/urls.py
from django.urls import path

from jobprofile.users.views import (
    AgentListView,
    AssignAgentView,
    CandidateRequestLike,
    ManagerCreateView,
    ManagerListView,
    UserCreateView,
    candidateRequestView,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("user/create/", view=UserCreateView.as_view(), name="user-create"),
    path("agent/assign/", view=AssignAgentView.as_view(), name="agent-assign"),
    path("agent/list/", view=AgentListView.as_view(), name="agent-list"),
    path("manager/create/", view=ManagerCreateView.as_view(), name="manager-create"),
    path("manager/list/", view=ManagerListView.as_view(), name="manager-list"),
    path("candidate", view=candidateRequestView.as_view(), name="candidate-list"),
    path(
        "candidate/update/<int:pk>",
        view=CandidateRequestLike.as_view(),
        name="candidate-like",
    ),
]

jobprofile/candidate/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from PIL import Image


class CandidateProfile(models.Model):
    PROFILE_STATE = (
        ("new", _("NEW")),
        ("active", _("ACTIVE")),
        ("rejected", _("REJECTED")),
        ("assigned", _("ASSIGNED")),
        ("closed", _("CLOSED")),
    )

    REF_MEDIA = (("agent", _("AGENT")), ("other", _("SOCIAL")))
    name = models.CharField(_("Your Name"), max_length=100)
    phone_number = models.CharField(_("Mobile No"), max_length=10)
    birth_date = models.DateField(_("Date Of Birth"), auto_now=False)
    email = models.EmailField(_("Mail Id"), unique=True)
    address = models.TextField(_("Address"))
    profile_state = models.CharField(
        _("Profile State"), max_length=80, choices=PROFILE_STATE, default="new"
    )
    reference = models.CharField(
        _("Our Reference"), max_length=80, choices=REF_MEDIA, default="other"
    )
    profile_pic = models.ImageField(_("Your profile Pic"))
    reference_details = models.CharField(_("Reference Provider"), max_length=30)
    language = models.TextField(_("Language Know"))

    def __str__(self):
        return f"{self.name} Profile!"

    def save(self):
        super().save()
        img = Image.open(self.profile_pic.path)
        if img.height > 300 or img.width > 300:
            output_size = (50, 50)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)


class Study(models.Model):
    name = models.CharField(_("Institute Name"), max_length=70)
    standard = models.CharField(_("Standard Name"), max_length=100)
    percentage = models.FloatField(_("Percentage"))
    year = models.DateField(_("Year"))
    candidate = models.ForeignKey(
        "CandidateProfile", on_delete=models.CASCADE, related_name="study"
    )
    course = models.TextField(_("Special Course"), null=True)
    cgpa = models.FloatField(_("Your CGPA"), null=True)

    def __str__(self):
        return f"{self.name} Study"


class Experience(models.Model):
    company = models.CharField(_("Company Name"), max_length=60)
    latter = models.ImageField(_("Company Experience Latter"), max_length=60, null=True)
    start_date = models.DateField(_("Join Date"), auto_now=False)
    end_date = models.DateField(_("End Date"), auto_now=False)
    role = models.CharField(_("Previous Company Role"), max_length=80, null=True)
    New_role = models.CharField(
        _("Looking For Role"), default="developer", max_length=80
    )
    candidate = models.ForeignKey(
        "CandidateProfile", on_delete=models.CASCADE, related_name="experience"
    )
    description = models.TextField(_("Job Description"))

    def __str__(self):
        return f"{self.company} Company"


class Skill(models.Model):
    candidate = models.ForeignKey(
        "CandidateProfile", on_delete=models.CASCADE, related_name="can_skill"
    )
    skill_level = models.IntegerField(
        _("Skill Level"),
        null=True,
    )
    technical_skill = models.TextField(_("Technical Skills"))
    soft_skill = models.TextField(_("Soft Skill"))
    project = models.TextField(_("Project Details"))

    def __str__(self):
        return f"{self.skill} Technical"

jobprofile/users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for jobprofile.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    is_manager = models.BooleanField(_("manager status"), default=False)
    is_agent = models.BooleanField(_("agent status"), default=False)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})


class Manager(models.Model):
    sector = models.CharField(_("Sector"), max_length=50)
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE, related_name="manager"
    )

    def __str__(self):
        return f"{self.user} Manager"


class Agent(models.Model):
    code = models.CharField(_("Code"), max_length=10)
    manager = models.ForeignKey(
        "Manager",
        on_delete=models.CASCADE,
        verbose_name="Manager Id",
        related_name="agent",
    )
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE, related_name="agent"
    )

    def __str__(self):
        return f"{self.user} Agent"

jobprofile/candidate/forms.py
from django import forms

from .models import CandidateProfile, Experience, Study


class CandidateProfileForm(forms.ModelForm):
    class Meta:
        model = CandidateProfile
        fields = [
            "name",
            "phone_number",
            "email",
            "birth_date",
            "reference",
            "address",
            "profile_pic",
            "reference",
            "reference_details",
            "language",
        ]
        widgets = {"birth_date": forms.DateInput(attrs={"type": "date"})}


class CandidateStudyForm(forms.ModelForm):
    class Meta:
        model = Study
        fields = ["name", "standard", "percentage", "year", "course", "cgpa"]
        widgets = {
            "year": forms.DateInput(attrs={"type": "date"}),
            "course": forms.TextInput(),
        }


class CandidateExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = [
            "company",
            "latter",
            "start_date",
            "end_date",
            "role",
            "New_role",
            "description",
        ]
        widgets = {
            "start_date": forms.DateInput(attrs={"type": "date"}),
            "end_date": forms.DateInput(attrs={"type": "date"}),
        }

jobprofile/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class UserRegisatrtionForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password", "email", "is_agent", "is_manager"]
        widgets = {"password": forms.PasswordInput()}

jobprofile/candidate/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView

from .forms import CandidateExperienceForm, CandidateProfileForm, CandidateStudyForm


class CreateCandidateProfileView(SuccessMessageMixin, CreateView):

    template_name = "candidate/candidate_form.html"
    success_url = reverse_lazy("home")
    form_class = CandidateProfileForm
    success_message = _("Information successfully Added")

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["candidate_experience"] = CandidateExperienceForm(self.request.POST)
        context["candidate_study"] = CandidateStudyForm(self.request.POST)
        return context

    def form_valid(self, form):
        candidate = form.save()
        candidate_experience = self.get_form(form_class=CandidateExperienceForm)
        candidate_experience.instance.candidate_id = candidate.id
        candidate_study = self.get_form(form_class=CandidateStudyForm)
        candidate_study.instance.candidate_id = candidate.id
        if candidate_experience.is_valid() and candidate_study.is_valid():
            candidate_experience.save()
            candidate_study.save()
        return super().form_valid(form)

jobprofile/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    RedirectView,
    UpdateView,
)

from jobprofile.candidate.models import CandidateProfile

from .forms import UserRegisatrtionForm
from .models import Agent, Manager

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name", "is_manager"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserTypeCheckMixin(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin):
    def test_func(self):
        return (
            True
            if self.request.user.is_manager or self.request.user.is_superuser
            else False
        )


class UserCreateView(UserTypeCheckMixin, CreateView):

    form_class = UserRegisatrtionForm
    template_name = "pages/registration_form.html"
    model = User
    success_message = _("User Create successfully")

    def form_valid(self, form):
        form.instance.set_password(form.cleaned_data["password"])
        return super().form_valid(form)


class AssignAgentView(UserTypeCheckMixin, CreateView):

    model = Agent
    template_name = "pages/assign_agent.html"
    fields = ["code", "user"]
    success_url = reverse_lazy("home")
    success_message = _("Agent Assign Successfully ")

    def form_valid(self, form):
        form.instance.manager_id = self.request.user.manager.id
        form.save()
        return super(AssignAgentView, self).form_valid(form)


class AgentListView(UserTypeCheckMixin, ListView):

    model = Agent
    template_name = "pages/agent_list.html"

    def get_queryset(self):
        agents_list = Agent.objects.filter(manager_id=self.request.user.manager.id)
        search_list = self.request.GET.get("search_list")
        if search_list:
            agents_list = Agent.objects.filter(code__icontains=search_list)
            return agents_list
        return agents_list


class ManagerCreateView(UserTypeCheckMixin, CreateView):

    model = Manager
    template_name = "pages/manager_form.html"
    fields = ["user", "sector"]
    success_url = "/"
    success_message = _("Manager Create successfully.")
    context = User.objects.filter(is_manager="True")

    def test_func(self):
        return True if self.request.user.is_superuser else False


class ManagerListView(UserTypeCheckMixin, ListView):

    model = Manager
    template_name = "pages/manager_list.html"

    def test_func(self):
        return True if self.request.user.is_superuser else False


class candidateRequestView(UserTypeCheckMixin, ListView):

    model = CandidateProfile
    template_name = "pages/candidate_request.html"

    def test_func(self):
        return (
            True
            if self.request.user.is_manager or self.request.user.agent.code
            else False
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        if self.request.user.is_manager:
            context["other"] = CandidateProfile.objects.filter(reference="other")
            context["candidates"] = CandidateProfile.objects.filter(
                reference_details__in=self.request.user.manager.agent.all().values_list(
                    "code", flat=True
                )
            )
            return context
        elif self.request.user.is_agent:
            context["candidates"] = CandidateProfile.objects.filter(
                reference_details=self.request.user.agent.code
            )
        return context


class CandidateRequestLike(UserTypeCheckMixin, UpdateView):

    model = CandidateProfile
    template_name = "pages/update_profile.html"
    fields = ["profile_state"]
    success_url = reverse_lazy("users:candidate-list")
    success_message = _("Profile Updated successfully")

    def test_func(self):
        return True if self.request.user.is_manager else False

jobprofile/templates/pages/about.html
{% extends "base.html" %}

jobprofile/templates/pages/agent_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="text-center display-5"> {{request.user.username}} Manager</div>
  <table class="table">
    <thead>
    <th> code</th>
    <th> user</th>
    </thead>
    <tbody>
    {% for agent in object_list %}
    <tr>
      <td> {{agent.code}}</td>
      <td> {{agent.user}}</td>
    </tr>
    {% endfor %}
    <a class="btn btn-outline-secondary" href="{% url 'home' %}"> Main Page</a>
    <form>
      <input class=" m-2 p-1" type="text" name="search_list">
      <button class="btn btn-outline-secondary "> Search</button>
    </form>
    </tbody>
  </table>
</div>
</div>
{% endblock %}

jobprofile/templates/pages/assign_agent.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<form method="POST">
  {% csrf_token %}
  {{form|crispy}}
  <button type="submit" class="btn btn-outline-success"> Assign Agent</button>
  <a type="submit" class="btn btn-outline-danger" href="{% url 'home' %}"> Cancel </a>
</form>
</div>
{% endblock %}

jobprofile/templates/pages/candidate_request.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="text-center display-6"> {{request.user.username}} Welcome</div>
  <table class="table">
    <thead>
    <th> name</th>
    <th> phone_number</th>
    <th> reference_details</th>
    <th> Status</th>
    <th> profile_pic</th>
    <th> Action</th>
    </thead>
    <tbody>
    {% for candidate in candidates %}
    <tr>
      <td> {{candidate.name}}</td>
      <td> {{candidate.phone_number}}</td>
      <td> {{candidate.reference_details}}</td>
      <td> {{candidate.profile_state}}</td>
      <td> <img class="rounded-circle account-img" src="{{candidate.profile_pic.url}}"></td>
      <td><a href="{% url 'users:candidate-like' candidate.id  %}" class="btn btn-outline-success"> Open </a></td>
    </tr>
    {% endfor %}
    <a class="btn btn-outline-secondary" href="{% url 'home' %}"> Main Page</a>
    </tbody>
  </table>
  <table class="table">
    <thead>
    <h1> Social Media Request </h1>
    <tr>
      <th> name</th>
      <th> phone_number</th>
      <th> reference_details</th>
      <th> Status</th>
    </tr>
    </thead>
    <tbody>
    {% for candidate in other %}
    <tr>
      <td> {{candidate.name}}</td>
      <td> {{candidate.phone_number}}</td>
      <td> {{candidate.reference_details}}</td>
      <td> {{candidate.profile_state}}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock %}

jobprofile/templates/pages/home.html
{% extends "base.html" %}
{% block content%}
{% if request.user.is_manager %}
<small class="mt-2 mb-3"> welcome manager {{request.user.manager.id}}</small>
<div class="container">
  <div class="row">
      <div class="Card mr-auto col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:agent-assign' %}"> Assign Agent </a>
      </div>
      <div class="Card  col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:agent-list' %}"> Total Agent</a>
      </div>
    <div class="Card  col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:user-create' %}" > Create Agent  </a>
      </div>
  </div>
  <div class="row">
    <div class="Card mr-auto col-sm-4 my-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:candidate-list' %}"> Total Request</a>
      </div>
  </div>
</div>

{% elif request.user.is_agent %}
<small class="mt-2 mb-3"> welcome agent </small>
<div class="container">
  {% if request.user.agent %}
  <div class="row">
      <div class="Card mr-auto col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:candidate-list' %}"> Total Request </a>
      </div>
  </div>
  {% endif %}
</div>
{% elif request.user.is_superuser %}
<small class="mt-2 mb-3"> welcome superuser </small>
<div class="container">
  <div class="row">
      <div class="Card mr-auto col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:manager-create' %}"> Assign Manager </a>
      </div>
      <div class="Card  col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:manager-list' %}"> Manager List </a>
      </div>
    <div class="Card  col-sm-4">
        <a class="btn btn-outline-secondary" href="{% url 'users:user-create' %}" > Create User  </a>
      </div>
  </div>
</div>
{% else %}
<small>Upload Profile for Candidate  </small>
<div class="container">
  <a class="btn btn-outline-secondary m-2 p-2" href="{% url 'candidate:candidate' %}">Profile</a>
</div>
{% endif %}
{% endblock %}

jobprofile/templates/pages/manager_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{form|crispy}}
  <button type="submit" class="btn btn-outline-success"> Create Agent</button>
  <a type="submit" class="btn btn-outline-danger" href="{% url 'home' %}"> Cancel </a>
</form>
{% endblock %}

jobprofile/templates/pages/manager_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <table class="table">
      <thead>
      <th> department </th>
      <th> Manager </th>
      </thead>
      <tbody>
{% for manager in object_list %}
      <tr>
      <td> {{manager.sector}}</td>
      <td> {{manager.user}}</td>
        </tr>
{% endfor %}
      <a class="btn btn-outline-secondary" href="{% url 'home' %}"> Main Page</a>
      </tbody>
       </table>
  </div>
</div>
{% endblock %}

jobprofile/templates/pages/registration_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
{{ form.username|as_crispy_field }}
  {{ form.email|as_crispy_field }}
{{ form.password|as_crispy_field }}
  {% if request.user.is_manager%}
{{ form.is_agent|as_crispy_field }}
  {% elif request.user.is_superuser %}
{{ form.is_manager|as_crispy_field }}
  {% endif %}
<button type="submit" class="btn btn-outline-success"> Create Agent</button>
<a type="submit" class="btn btn-outline-danger" href="{% url 'home' %}"> Cancel </a>
</form>
{% endblock %}

jobprofile/templates/pages/update_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
  <div class="container col-sm-10">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-outline-success"> Update Profile</button>
    <a type="submit" class="btn btn-outline-danger" href="{% url 'home' %}"> Cancel </a>
  </div>
</form>
{% endblock %}